// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://agslsrysuytnjofjxcfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnc2xzcnlzdXl0bmpvZmp4Y2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3Nzk5ODAsImV4cCI6MjA4MDM1NTk4MH0.xiVVm0egTfSuJgVIBIlXuN93iw7ml2RvVRhA_k4acxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);